/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SequenceRouteImport } from './routes/sequence'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryIndexRouteImport } from './routes/story.index'
import { Route as StorySequenceIdRouteImport } from './routes/story.$sequenceId'
import { Route as SceneSceneIdRouteImport } from './routes/scene.$sceneId'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiEventsRouteImport } from './routes/api/events'

const SequenceRoute = SequenceRouteImport.update({
  id: '/sequence',
  path: '/sequence',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIndexRoute = StoryIndexRouteImport.update({
  id: '/story/',
  path: '/story/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorySequenceIdRoute = StorySequenceIdRouteImport.update({
  id: '/story/$sequenceId',
  path: '/story/$sequenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneSceneIdRoute = SceneSceneIdRouteImport.update({
  id: '/scene/$sceneId',
  path: '/scene/$sceneId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runs': typeof RunsRoute
  '/sequence': typeof SequenceRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRoute
  '/scene/$sceneId': typeof SceneSceneIdRoute
  '/story/$sequenceId': typeof StorySequenceIdRoute
  '/story/': typeof StoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runs': typeof RunsRoute
  '/sequence': typeof SequenceRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRoute
  '/scene/$sceneId': typeof SceneSceneIdRoute
  '/story/$sequenceId': typeof StorySequenceIdRoute
  '/story': typeof StoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/runs': typeof RunsRoute
  '/sequence': typeof SequenceRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/media': typeof ApiMediaRoute
  '/scene/$sceneId': typeof SceneSceneIdRoute
  '/story/$sequenceId': typeof StorySequenceIdRoute
  '/story/': typeof StoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/runs'
    | '/sequence'
    | '/api/events'
    | '/api/health'
    | '/api/media'
    | '/scene/$sceneId'
    | '/story/$sequenceId'
    | '/story/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/runs'
    | '/sequence'
    | '/api/events'
    | '/api/health'
    | '/api/media'
    | '/scene/$sceneId'
    | '/story/$sequenceId'
    | '/story'
  id:
    | '__root__'
    | '/'
    | '/runs'
    | '/sequence'
    | '/api/events'
    | '/api/health'
    | '/api/media'
    | '/scene/$sceneId'
    | '/story/$sequenceId'
    | '/story/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRoute: typeof RunsRoute
  SequenceRoute: typeof SequenceRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMediaRoute: typeof ApiMediaRoute
  SceneSceneIdRoute: typeof SceneSceneIdRoute
  StorySequenceIdRoute: typeof StorySequenceIdRoute
  StoryIndexRoute: typeof StoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sequence': {
      id: '/sequence'
      path: '/sequence'
      fullPath: '/sequence'
      preLoaderRoute: typeof SequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/': {
      id: '/story/'
      path: '/story'
      fullPath: '/story/'
      preLoaderRoute: typeof StoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$sequenceId': {
      id: '/story/$sequenceId'
      path: '/story/$sequenceId'
      fullPath: '/story/$sequenceId'
      preLoaderRoute: typeof StorySequenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene/$sceneId': {
      id: '/scene/$sceneId'
      path: '/scene/$sceneId'
      fullPath: '/scene/$sceneId'
      preLoaderRoute: typeof SceneSceneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRoute: RunsRoute,
  SequenceRoute: SequenceRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMediaRoute: ApiMediaRoute,
  SceneSceneIdRoute: SceneSceneIdRoute,
  StorySequenceIdRoute: StorySequenceIdRoute,
  StoryIndexRoute: StoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
